# Generated by Django 3.0.7 on 2020-06-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key',
            field=models.TextField(default='', verbose_name='key'),
        ),
    ]
